name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    # TODO: Add a step to restore dependencies using `dotnet restore`
    
    # TODO: Add a step to build the project using `dotnet build --no-restore`
    
    # TODO: Add a step to run tests using `dotnet test --no-build --verbosity normal`
